// =========================================================================
// lib/gpu/shader.c — HLSL shaders for instanced rendering + blur
// =========================================================================
#include "src/types.h"

// The vertex shader draws a full-screen quad using SV_VertexID,
// and the instance data provides position/size/texture/opacity/corner-radius.
// The pixel shader samples from either the BC1 texture array (t0),
// the full-image SRV (t1), the blur backdrop (t2), or renders solid
// colors based on the token constants.
const char *shader_src = "cbuffer Constants : register(b0) {\n"
                         "    float2 window_size;\n"
                         "    float dpi_scale;\n"
                         "    float padding;\n"
                         "};\n"
                         "cbuffer ThemeConstants : register(b1) {\n"
                         "    float4 theme_bg;\n"
                         "    float4 theme_panel;\n"
                         "    float4 theme_border;\n"
                         "    float4 theme_text_main;\n"
                         "    float4 theme_text_muted;\n"
                         "    float4 theme_accent;\n"
                         "    float4 theme_scrollbar;\n"
                         "};\n"
                         "struct VSOut {\n"
                         "    float4 pos : SV_Position;\n"
                         "    float2 uv : TEXCOORD;\n"
                         "    float2 size : INST_SIZE;\n"
                         "    int tex_index : INST_TEX;\n"
                         "    float opacity : INST_OPACITY;\n"
                         "    float corner_radius : INST_RADIUS;\n"
                         "};\n"
                         "Texture2DArray<float4> tex_array : register(t0);\n"
                         "Texture2D<float4> full_image : register(t1);\n"
                         "Texture2D<float4> blur_tex : register(t2);\n"
                         "SamplerState tex_sampler : register(s0);\n"
                         "\n"
                         "VSOut vs_main(uint id : SV_VertexID) {\n"
                         "    VSOut o;\n"
                         "    o.uv = float2(id & 1, (id >> 1) & 1);\n"
                         "    o.pos = float4(o.uv * 2.0 - 1.0, 0.0, 1.0);\n"
                         "    o.size = 1;\n"
                         "    o.tex_index = 0;\n"
                         "    o.opacity = 1;\n"
                         "    o.corner_radius = 0;\n"
                         "    return o;\n"
                         "}\n"
                         "\n"
                         "// 25-tap Gaussian blur (5x5 kernel, single pass)\n"
                         "static const float blur_weights[25] = {\n"
                         "    0.003765, 0.015016, 0.023792, 0.015016, 0.003765,\n"
                         "    0.015016, 0.059912, 0.094907, 0.059912, 0.015016,\n"
                         "    0.023792, 0.094907, 0.150342, 0.094907, 0.023792,\n"
                         "    0.015016, 0.059912, 0.094907, 0.059912, 0.015016,\n"
                         "    0.003765, 0.015016, 0.023792, 0.015016, 0.003765\n"
                         "};\n"
                         "static const float2 blur_offsets[25] = {\n"
                         "    float2(-2,-2), float2(-1,-2), float2(0,-2), float2(1,-2), float2(2,-2),\n"
                         "    float2(-2,-1), float2(-1,-1), float2(0,-1), float2(1,-1), float2(2,-1),\n"
                         "    float2(-2,0),  float2(-1,0),  float2(0,0),  float2(1,0),  float2(2,0),\n"
                         "    float2(-2,1),  float2(-1,1),  float2(0,1),  float2(1,1),  float2(2,1),\n"
                         "    float2(-2,2),  float2(-1,2),  float2(0,2),  float2(1,2),  float2(2,2)\n"
                         "};\n"
                         "\n"
                         "float4 ps_main(VSOut i) : SV_Target {\n"
                         "    float2 win = window_size;\n"
                         "    float dpi = dpi_scale;\n"
                         "\n"
                         "    // --- Token-based rendering ---\n"
                         "    int t = i.tex_index;\n"
                         "\n"
                         "    // TOKEN_BORDER (1) — border color\n"
                         "    if (t == 1) {\n"
                         "        return float4(theme_border.rgb, i.opacity);\n"
                         "    }\n"
                         "\n"
                         "    // TOKEN_PANEL (2) — panel background\n"
                         "    if (t == 2) {\n"
                         "        return float4(theme_panel.rgb, i.opacity);\n"
                         "    }\n"
                         "\n"
                         "    // TOKEN_SCROLLBAR (3) — scrollbar thumb\n"
                         "    if (t == 3) {\n"
                         "        return float4(theme_scrollbar.rgb, i.opacity * theme_scrollbar.a);\n"
                         "    }\n"
                         "\n"
                         "    // TOKEN_FULL_IMAGE (4) — sample from full-image SRV (t1)\n"
                         "    if (t == 4) {\n"
                         "        float2 tex_size;\n"
                         "        full_image.GetDimensions(tex_size.x, tex_size.y);\n"
                         "        if (tex_size.x > 0 && tex_size.y > 0) {\n"
                         "            float2 uv = (i.pos.xy - float2(0,0)) / float2(win.x, win.y);\n"
                         "            uv = uv * win / tex_size;\n"
                         "            return float4(full_image.Sample(tex_sampler, uv).rgb, i.opacity);\n"
                         "        }\n"
                         "        return float4(0,0,0,0);\n"
                         "    }\n"
                         "\n"
                         "    // TOKEN_DROP_SHADOW (5) — soft shadow under panels\n"
                         "    if (t == 5) {\n"
                         "        float dx = 4.0 * dpi;\n"
                         "        float shadow_alpha = 0.35 * i.opacity;\n"
                         "        float2 pos = i.pos.xy / win;\n"
                         "        float2 shadow_uv = (i.pos.xy - float2(0, 6 * dpi)) / (i.size * dpi);\n"
                         "        float blur = 1.0 - length(shadow_uv - 0.5) * 2.0;\n"
                         "        return float4(0, 0, 0, saturate(blur * shadow_alpha));\n"
                         "    }\n"
                         "\n"
                         "    // TOKEN_ACCENT (6) — accent selection border\n"
                         "    if (t == 6) {\n"
                         "        return float4(theme_accent.rgb, i.opacity);\n"
                         "    }\n"
                         "\n"
                         "    // TOKEN_SELECTION_OUTLINE (7) — glowing selection outline\n"
                         "    if (t == 7) {\n"
                         "        return float4(theme_accent.rgb, i.opacity);\n"
                         "    }\n"
                         "\n"
                         "    // TOKEN_BLUR (8) — blur backplate sample from blur_tex (t2)\n"
                         "    if (t == 8) {\n"
                         "        float2 tex_size;\n"
                         "        blur_tex.GetDimensions(tex_size.x, tex_size.y);\n"
                         "        if (tex_size.x > 0 && tex_size.y > 0) {\n"
                         "            float2 uv = i.pos.xy / win;\n"
                         "            float2 tex_uv = uv * win / tex_size;\n"
                         "            float4 blur_color = float4(0,0,0,0);\n"
                         "            for (int k = 0; k < 25; k++) {\n"
                         "                float2 sample_uv = tex_uv + blur_offsets[k] / tex_size;\n"
                         "                blur_color += blur_tex.Sample(tex_sampler, sample_uv) * blur_weights[k];\n"
                         "            }\n"
                         "            return float4(blur_color.rgb * theme_panel.rgb, i.opacity);\n"
                         "        }\n"
                         "        return float4(theme_panel.rgb, i.opacity);\n"
                         "    }\n"
                         "\n"
                         "    // TOKEN_DEFAULT (0) or anything else — sample from BC1 texture array\n"
                         "    if (t >= 0 && i.size.x > 0 && i.size.y > 0) {\n"
                         "        float2 uv = i.uv * float2(i.size.x / (160 * dpi), i.size.y / (160 * dpi));\n"
                         "        float4 tex = tex_array.Sample(tex_sampler, float3(uv, t));\n"
                         "        return float4(tex.rgb, i.opacity);\n"
                         "    }\n"
                         "\n"
                         "    return float4(theme_bg.rgb, 1.0);\n"
                         "}\n";
