// =========================================================================
// lib/gpu/shader.c — HLSL shaders for instanced rendering + blur
// =========================================================================
#include "src/types.h"

// The vertex shader draws a full-screen quad using SV_VertexID,
// and the instance data provides position/size/texture/opacity/corner-radius.
// The pixel shader samples from either the BC1 texture array (t0),
// the full-image SRV (t1), the blur backdrop (t2), or renders solid
// colors based on the token constants.
const char *shader_src = "cbuffer Constants : register(b0) {\n"
                         "    float2 window_size;\n"
                         "    float dpi_scale;\n"
                         "    float padding;\n"
                         "};\n"
                         "cbuffer ThemeConstants : register(b1) {\n"
                         "    float4 theme_bg;\n"
                         "    float4 theme_panel;\n"
                         "    float4 theme_border;\n"
                         "    float4 theme_text_main;\n"
                         "    float4 theme_text_muted;\n"
                         "    float4 theme_accent;\n"
                         "    float4 theme_scrollbar;\n"
                         "};\n"
                         "struct VS_INPUT {\n"
                         "    uint vertex_id : SV_VertexID;\n"
                         "    float2 pos : INST_POS;\n"
                         "    float2 size : INST_SIZE;\n"
                         "    int tex_idx : INST_TEX;\n"
                         "    float opacity : INST_OPACITY;\n"
                         "    float radius : INST_RADIUS;\n"
                         "};\n"
                         "struct PS_INPUT {\n"
                         "    float4 pos : SV_Position;\n"
                         "    float2 uv : TEXCOORD;\n"
                         "    int tex_idx : TEX_INDEX;\n"
                         "    float opacity : OPACITY;\n"
                         "    float2 size : SIZE;\n"
                         "    float radius : RADIUS;\n"
                         "};\n"
                         "Texture2DArray<float4> tex_array : register(t0);\n"
                         "Texture2D<float4> full_image : register(t1);\n"
                         "Texture2D<float4> blur_tex : register(t2);\n"
                         "SamplerState tex_sampler : register(s0);\n"
                         "\n"
                         "static const float2 uvs[4] = { float2(0,0), float2(1,0), float2(0,1), float2(1,1) };\n"
                         "\n"
                         "PS_INPUT vs_main(VS_INPUT input) {\n"
                         "    PS_INPUT output;\n"
                         "    float2 uv = uvs[input.vertex_id];\n"
                         "    float2 pixel_pos = input.pos + uv * input.size;\n"
                         "    pixel_pos.x = (pixel_pos.x / window_size.x) * 2.0 - 1.0;\n"
                         "    pixel_pos.y = 1.0 - (pixel_pos.y / window_size.y) * 2.0;\n"
                         "    output.pos = float4(pixel_pos, 0.0, 1.0);\n"
                         "    output.uv = uv;\n"
                         "    output.tex_idx = input.tex_idx;\n"
                         "    output.opacity = input.opacity;\n"
                         "    output.size = input.size;\n"
                         "    output.radius = input.radius;\n"
                         "    return output;\n"
                         "}\n"
                         "\n"
                         "// Rounded-rectangle signed-distance field\n"
                         "float rounded_rect_sdf(float2 p, float2 size, float radius) {\n"
                         "    float2 half_size = size * 0.5;\n"
                         "    float2 d = abs(p - half_size) - half_size + radius;\n"
                         "    return min(max(d.x, d.y), 0.0) + length(max(d, 0.0)) - radius;\n"
                         "}\n"
                         "\n"
                         "// 25-tap Gaussian blur (5x5 kernel, single pass)\n"
                         "static const float blur_weights[25] = {\n"
                         "    0.003765, 0.015016, 0.023792, 0.015016, 0.003765,\n"
                         "    0.015016, 0.059912, 0.094907, 0.059912, 0.015016,\n"
                         "    0.023792, 0.094907, 0.150342, 0.094907, 0.023792,\n"
                         "    0.015016, 0.059912, 0.094907, 0.059912, 0.015016,\n"
                         "    0.003765, 0.015016, 0.023792, 0.015016, 0.003765\n"
                         "};\n"
                         "static const float2 blur_offsets[25] = {\n"
                         "    float2(-2,-2), float2(-1,-2), float2(0,-2), float2(1,-2), float2(2,-2),\n"
                         "    float2(-2,-1), float2(-1,-1), float2(0,-1), float2(1,-1), float2(2,-1),\n"
                         "    float2(-2,0),  float2(-1,0),  float2(0,0),  float2(1,0),  float2(2,0),\n"
                         "    float2(-2,1),  float2(-1,1),  float2(0,1),  float2(1,1),  float2(2,1),\n"
                         "    float2(-2,2),  float2(-1,2),  float2(0,2),  float2(1,2),  float2(2,2)\n"
                         "};\n"
                         "\n"
                         "float4 ps_main(PS_INPUT i) : SV_Target {\n"
                         "    float2 pixel_pos = i.uv * i.size;\n"
                         "    float d = rounded_rect_sdf(pixel_pos, i.size, i.radius);\n"
                         "    float alpha = (i.tex_idx == -6) ? clamp(-d / 12.0, 0.0, 1.0) * 0.35 : ((i.tex_idx == -8) ? clamp(0.5 "
                         "- abs(d + 1.25) + 1.25, 0.0, 1.0) : clamp(0.5 - d, 0.0, 1.0));\n"
                         "    if (alpha <= 0.0) discard;\n"
                         "    float4 color;\n"
                         "    if (i.tex_idx == -2) color = theme_border;\n"
                         "    else if (i.tex_idx == -3) color = theme_panel;\n"
                         "    else if (i.tex_idx == -4) color = theme_scrollbar;\n"
                         "    else if (i.tex_idx == -5) color = full_image.Sample(tex_sampler, i.uv);\n"
                         "    else if (i.tex_idx == -6) color = float4(0.0, 0.0, 0.0, 1.0);\n"
                         "    else if (i.tex_idx == -7) color = theme_accent;\n"
                         "    else if (i.tex_idx == -8) color = theme_accent;\n"
                         "    else if (i.tex_idx == -9) {\n"
                         "        float2 uv = i.pos.xy / window_size;\n"
                         "        float2 texel = (1.5 * dpi_scale) / window_size;\n"
                         "        float4 sum = 0.0;\n"
                         "        sum += blur_tex.SampleLevel(tex_sampler, uv, 2.5) * 0.16;\n"
                         "        sum += blur_tex.SampleLevel(tex_sampler, uv + float2( 1.0,  0.0) * texel, 2.5) * 0.08;\n"
                         "        sum += blur_tex.SampleLevel(tex_sampler, uv + float2(-1.0,  0.0) * texel, 2.5) * 0.08;\n"
                         "        sum += blur_tex.SampleLevel(tex_sampler, uv + float2( 0.0,  1.0) * texel, 2.5) * 0.08;\n"
                         "        sum += blur_tex.SampleLevel(tex_sampler, uv + float2( 0.0, -1.0) * texel, 2.5) * 0.08;\n"
                         "        sum += blur_tex.SampleLevel(tex_sampler, uv + float2( 1.0,  1.0) * texel, 2.5) * 0.04;\n"
                         "        sum += blur_tex.SampleLevel(tex_sampler, uv + float2(-1.0,  1.0) * texel, 2.5) * 0.04;\n"
                         "        sum += blur_tex.SampleLevel(tex_sampler, uv + float2( 1.0, -1.0) * texel, 2.5) * 0.04;\n"
                         "        sum += blur_tex.SampleLevel(tex_sampler, uv + float2(-1.0, -1.0) * texel, 2.5) * 0.04;\n"
                         "        sum += blur_tex.SampleLevel(tex_sampler, uv + float2( 2.0,  0.0) * texel, 2.5) * 0.04;\n"
                         "        sum += blur_tex.SampleLevel(tex_sampler, uv + float2(-2.0,  0.0) * texel, 2.5) * 0.04;\n"
                         "        sum += blur_tex.SampleLevel(tex_sampler, uv + float2( 0.0,  2.0) * texel, 2.5) * 0.04;\n"
                         "        sum += blur_tex.SampleLevel(tex_sampler, uv + float2( 0.0, -2.0) * texel, 2.5) * 0.04;\n"
                         "        sum += blur_tex.SampleLevel(tex_sampler, uv + float2( 2.0,  2.0) * texel, 2.5) * 0.02;\n"
                         "        sum += blur_tex.SampleLevel(tex_sampler, uv + float2(-2.0,  2.0) * texel, 2.5) * 0.02;\n"
                         "        sum += blur_tex.SampleLevel(tex_sampler, uv + float2( 2.0, -2.0) * texel, 2.5) * 0.02;\n"
                         "        sum += blur_tex.SampleLevel(tex_sampler, uv + float2(-2.0, -2.0) * texel, 2.5) * 0.02;\n"
                         "        sum += blur_tex.SampleLevel(tex_sampler, uv + float2( 3.0,  0.0) * texel, 2.5) * 0.02;\n"
                         "        sum += blur_tex.SampleLevel(tex_sampler, uv + float2(-3.0,  0.0) * texel, 2.5) * 0.02;\n"
                         "        sum += blur_tex.SampleLevel(tex_sampler, uv + float2( 0.0,  3.0) * texel, 2.5) * 0.02;\n"
                         "        sum += blur_tex.SampleLevel(tex_sampler, uv + float2( 0.0, -3.0) * texel, 2.5) * 0.02;\n"
                         "        sum += blur_tex.SampleLevel(tex_sampler, uv + float2( 3.0,  3.0) * texel, 2.5) * 0.01;\n"
                         "        sum += blur_tex.SampleLevel(tex_sampler, uv + float2(-3.0,  3.0) * texel, 2.5) * 0.01;\n"
                         "        sum += blur_tex.SampleLevel(tex_sampler, uv + float2( 3.0, -3.0) * texel, 2.5) * 0.01;\n"
                         "        sum += blur_tex.SampleLevel(tex_sampler, uv + float2(-3.0, -3.0) * texel, 2.5) * 0.01;\n"
                         "        color.rgb = lerp(sum.rgb, theme_panel.rgb, 0.6);\n"
                         "        color.a = 1.0;\n"
                         "    }\n"
                         "    else if (i.tex_idx < 0) color = theme_panel;\n"
                         "    else color = tex_array.Sample(tex_sampler, float3(i.uv, i.tex_idx));\n"
                         "    color.a *= i.opacity * alpha;\n"
                         "    color.rgb *= color.a;\n"
                         "    return color;\n"
                         "}\n";
